id: PE64D0625
initial_creation_type: input
source_metadata:
  title: Kagyé Series
  language: en
  description: 'Texts related to the Kagyé (bka’ brgyad), the Eight Command Deities
    or Eight Herukas:'
  volume:
    1222e7328be04158be30174f5775f687:
      title: Daily Practice of Kagyé
      parent: Sādhanas
    3bcdb60c4a434b55ac4acf7d4179e9e7:
      title: The Essential Activity Manual for the Awesome Ones’ Assembly, the Heart
        Practice of Vidyādharas, from the Heart Essence of the Vast Expanse
      parent: Sādhanas
    47f91fc02e3a4b87badb91351005a223:
      title: 'The Single Mudrā: A Daily Practice for the Awesome Ones’ Assembly (Palchen
        Düpa), the Heart Practice of the Awareness-Holders'
      parent: Sādhanas
    190d2c3928f4436ba8a63acc8aefbc12:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Sādhanas
created_at: '2022-03-01T04:01:53.764013'
last_modified_at: '2022-03-01T04:01:53.764019'
